version: "3.8"

volumes:
  postgres:
  redis:
    driver: local

services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres
    ports:
      - 9000:9000
      - 2345:2345

    volumes:
      - .:/usr/src/app:rw

  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
